### ISSUE TITLE
Criar o plano de gerência de configuração e mudanças do projeto

### ISSUE THREAD

**Issue by Barbozah** [WildCatDevelopment/sistema-docente#26]
Criar o plano de gerenciamento de configuração.

**Comment by brunohgv** [comment]
Documento disponível em: https://docs.google.com/document/d/1ITtmzmBL85wowvdRG7prsnnezyZ_kJy2_PmT87Mkdd4/edit?usp=sharing

**Comment by brunohgv** [comment]
Wiki atualizada com link para documento

**Comment by Barbozah** [comment]
Link do arquivo de configuração: https://docs.google.com/document/d/1ITtmzmBL85wowvdRG7prsnnezyZ_kJy2_PmT87Mkdd4/edit?usp=sharing
