### ISSUE TITLE
Preenchimento do PM canvas

### ISSUE THREAD

**Issue by brunohgv** [WildCatDevelopment/sistema-docente#3]
Preencher PM canvas com as informações referentes ao projeto.

![image](https://user-images.githubusercontent.com/21175767/56543493-01936b80-6548-11e9-8528-4ce8cda3e7f6.png)

**Comment by Barbozah** [comment]
![Sistema de gerenciamento de Docentes](https://user-images.githubusercontent.com/34846614/56927711-3bfe8a80-6aab-11e9-835a-0f7834376780.png)
